version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_express_template:/var/lib/postgresql/data

volumes:
  postgres_data_express_template: